name: Build check

on:
  push:
    paths-ignore:
      - '**.md'
      - 'images/**'
  pull_request:
    types: [assigned, edited, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      # step 2: checkout repository code
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2

      # step 3: install dependencies
      - name: Install all Go dependencies
        run: go get

      # step 4: Run gofmt
      - name: Check that code complies with gofmt requirements
        run: make fmtcheck

      # step 5: source code static analysis
      - name: Run a source code static analysis plus a number of other checkers
        run: make lint

      # step 4: run test
      - name: Run the tests
        run: make test
